FROM lyft/envoy:latest
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y  software-properties-common && \
    add-apt-repository ppa:webupd8team/java -y && \
    apt-get update && \
    echo oracle-java7-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections && \
    apt-get install -y oracle-java8-installer && \
    apt-get clean
RUN mkdir /var/log/envoy/
CMD java -jar /home/customer-plan-assembly-1.0.jar & /usr/local/bin/envoy -c /etc/envoy-customer-server.json
