version: '2'
services:

  envoy_client:
    build:
      context: .
      dockerfile: dockerfile-smart-proxy
    volumes:
      - ./config/envoy-smart-proxy-config.json:/etc/envoy-config.json
    expose:
      - "8181"
    ports:
      - "8181:8181"