version: '2'
services:

  smart_proxy:
    build:
      context: .
      dockerfile: Dockerfile-smart-proxy
    volumes:
      - ./config/envoy-smart-proxy-config.json:/etc/envoy-smart-proxy-config.json
      - ./config/translate-proxy-assembly-1.0.jar:/home/translate-proxy-assembly-1.0.jar
    expose:
      - "8181"
    ports:
      - "8181:8181"

  envoy_client:
    build:
      context: .
      dockerfile: Dockerfile-customer_client
    volumes:
      - ./config/envoy-customer-client.json:/etc/envoy-customer-client.json
      - ./config/customer-service-assembly-1.0.jar:/home/customer-service-assembly-1.0.jar
    ports:
      - "8080:8080"
      - "9901:9901"

  envoy_server:
    build:
      context: .
      dockerfile: Dockerfile-customer_server
    volumes:
      - ./config/envoy-customer-server.json:/etc/envoy-customer-server.json
      - ./config/customer-plan-assembly-1.0.jar:/home/customer-plan-assembly-1.0.jar
    expose:
      - "50052"
    ports:
      - "50052:50052"
      - "9902:9902"